sudo: false
language: node_js

node_js:
  - "8"
  - "10"
  - "node"

cache:
  directories:
    - node_modules
    - $HOME/.npm

script: "npm run test"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
